ConfigWipe = {
    ESX = "",
    MessageWipe = "Vous avez été wipe, pattientez quelques minutes avant de relancer votre jeu !",

    Autorized = {
        ["fondateur"] = true,
        ["gerant"] = true,
        ['admin'] = true,
    },

    Logs = {
        WebHook = exports.Tree:serveurConfig().Logs.WipePlayers
    },

    WeaponPerm = {
        ['WEAPON_ASSAULTRIFLE'] = false,
        ['WEAPON_PAN'] = true,
        ['WEAPON_KATANA'] = true,
        ['WEAPON_TRIDAGGER'] = true,
        ['WEAPON_LUCILE'] = true,
        ['WEAPON_BAYONET'] = true,
        ['WEAPON_KARAMBIT'] = true,
        ['WEAPON_HEAVYSNIPER'] = true,
        ['WEAPON_CARBINERIFLE_MK2'] = true,
        ['WEAPON_ASSAULTSHOTGUN'] = true,
        ['WEAPON_SPECIALCARBINE'] = true,
        ['WEAPON_COMBATPDW'] = true,
        ['WEAPON_REVOLVER_MK2'] = true,
        ['WEAPON_MARSKSMANRIFLE'] = true,
        ['weapon_combatmg_mk2'] = true,
        ['WEAPON_M4A1FM'] = true,
        ['WEAPON_SCAR17FM'] = true,
        ['weapon_heavyshotgun'] = true,
        ['weapon_heavysniper_mk2'] = true,
        ['WEAPON_MP5SDFM'] = true,
        ['WEAPON_SR25'] = true,
        ['WEAPON_APPISTOL'] = true,
        ['WEAPON_MIDASGUN'] = true,
        ['WEAPON_GOLDM'] = true,
        ['WEAPON_REDL'] = true,
        ['WEAPON_AKORUS'] = true,
        ['WEAPON_MILITARM4'] = true,
        ['WEAPON_PREDATOR'] = true,
        ['WEAPON_BLASTAK'] = true,
        ['WEAPON_BLASTM4'] = true,
        ['WEAPON_BLACKSNIPER'] = true,
        ['WEAPON_CHAINSAW'] = true,
        ['WEAPON_DESERTPURPLE'] = true,
        ['WEAPON_REVOLVERVAMP'] = true,
        ['WEAPON_SPIDERAK'] = true,
        ['WEAPON_PUMPKIN'] = true,
        ['WEAPON_BONEPER'] = true,
        ['WEAPON_SIG550'] = true,
        ['WEAPON_REVOLVERULTRA'] = true,
        ['WEAPON_COACHGUN'] = true,
        ['WEAPON_SHOTGUNK'] = true,
        ['WEAPON_VSCO'] = true,
        ['WEAPON_BLUERIOT'] = true,
        ['WEAPON_ANCIENT'] = true,
        ['WEAPON_SNAKE'] = true,
        ['WEAPON_HELL'] = true,
        ['WEAPON_OBLIVION'] = true,
        ['WEAPON_KINETIC'] = true,
        ['WEAPON_TEC9M'] = true,
        ['WEAPON_TEC9MF'] = true,
        ['WEAPON_TEC9MB'] = true,
        ['WEAPON_SCARSC'] = true,
        ['WEAPON_SOVEREIGN'] = true,
        ['WEAPON_GLOCK17'] = true,
        ['WEAPON_ALIEN'] = true,
        ['WEAPON_MIDGARD'] = true,
        ['WEAPON_MAZE'] = true,
        ['WEAPON_PENIS'] = true,
        ['WEAPON_SPECIALHAMMER'] = true,
        ['WEAPON_GUARD'] = true,
        ['WEAPON_GRAU'] = true,
        ['WEAPON_SCAR17'] = true,
        ['WEAPON_M19'] = true,
        ['WEAPON_UZILS'] = true,
        ['WEAPON_DESERTNIKE'] = true,
        ['WEAPON_GLOCKDM'] = true,
        ['WEAPON_M4BEAST'] = true,
        ['WEAPON_M4GOLDBEAST'] = true,
        ['WEAPON_HELLSNIPER'] = true,
        ['WEAPON_357'] = true,

    },

    -- Delete
    TableDelete = {
        {name = "account_info", id = "license"},
        {name = "clothes_data", id = "identifier"},
        {name = "kq_extra", id = "player"},
        {name = "phone_clock_alarms", id = "id"},
        {name = "properties_list", id = "owner"},
        {name = "staff", id = "license"},
        {name = "vehicleclaimsell", id = "owner"},
        {name = "vehicletosell", id = "owner"},
        {name = "user_licenses", id = "owner"},
        {name = "billing", id = "identifier"},
        {name = "playerstattoos", id = "identifier"},
        {name = "jail", id = "identifier"},
        {name = "phone_phones", id = "id"},
        {name = "phone_backups", id = "identifier"},
        {name = "phone_crypto", id = "identifier"},
    },

    -- Update 
    TableUpdate = {
        {tablename = "users", var = "firstname", id = "identifier", finalvalue = ""},
        {tablename = "users", var = "lastname", id = "identifier", finalvalue = ""},
        {tablename = "users", var = "position", id = "identifier", finalvalue = nil},
        {tablename = "users", var = "skin", id = "identifier", finalvalue = nil},
        {tablename = "users", var = "accounts", id = "identifier", finalvalue = nil},
        {tablename = "users", var = "inventory", id = "identifier", finalvalue = nil},
        {tablename = "users", var = "clothes", id = "identifier", finalvalue = nil},
        {tablename = "users", var = "job", id = "identifier", finalvalue = "unemployed"},
        {tablename = "users", var = "job2", id = "identifier", finalvalue = "unemployed2"},
        {tablename = "users", var = "job_grade", id = "identifier", finalvalue = 0},
        {tablename = "users", var = "job2_grade", id = "identifier", finalvalue = 0},
        {tablename = "users", var = "isDead", id = "identifier", finalvalue = 0},
    }

}